opa:
  authorization:
    url: "http://localhost:8181/v1/compile"

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/integrationTest
    username: admin
    password: MangaonTaNiny0!
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false