server:
  port: 8081

opa:
  authorization:
    url: "http://localhost:8181/v1/compile"
  datasource:
    entities-package-name: "com.example.opadatafilterdemo.repository"

  partial-request:
    query: "data.petclinic.authz.allow = true"
    unknowns:
      - "data.pets"
    log-partial-request: true
    user-attribute-to-http-header-map:
      organization: X-ORG-HEADER

spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:sql/init.sql'"
    username: "sa"
    password: ""

  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration"